tests:
  - type: run-cmd
    cmd: [build:test_list]
    profiles:
      - debug
      - asan
  - type: forbidden-patterns
    token:
      - <list>
      - <queue>
      - <deque>
      - <vector>
    hint: "Implement linked list"
  - type: report-score
    task: list
editable:
  - list.hpp
