tests:
  - type: catch-unit
    profiles:
      - debug
      - asan
    bin: test_list
  - type: forbidden-patterns
    substring:
      - <list>
      - <queue>
      - <deque>
      - <vector>
    hint: "Implement linked list yourself"
editable:
  - list.hpp
