tests:
  - type: run-cmd
    cmd: [python3, tool:nej-runner, --checker, ignore-spaces, --run-cmd, build:solution_binary_tree_2]
    profiles:
      - asan
      - release
  - type: forbidden-patterns
    token:
      - read
      - pread
      - cin
      - ifstream
      - fstream
      - fopen
    hint: "Use mmap for file IO"
  - type: report-score
    task: binary-tree-2
editable:
  - solution.cpp
